spring:
  application:
    name: employee-service-feign-client

server: 
  port: 8005      

    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# Must have Hystrix on the classpath and also set feign.hystrix.enabled=true to have Feign automatically wrap methods in Hystrix commands.      
feign:
  hystrix:
    enabled: true
    
# To exposes the /actuator/hystrix.stream as a management endpoint for Hystrix Service for monitoring
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream