spring:
  application:
    name: employee-service-feign-client

server: 
  port: 8005      

    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# Must have Hystrix on the classpath and also set feign.hystrix.enabled=true to have Feign automatically wrap methods in Hystrix commands.      
feign:
  hystrix:
    enabled: true